spring:
  datasource:
    url: jdbc:mysql://localhost:3306/d206?serverTimezone=Asia/Seoul
    username: root
    password: ssafy
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    generate-ddl: false
    database: mysql

  logging:
    level:
      org.hibernate.sql: debug
      root: info
